---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php7-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app : php-site
  template:
    metadata:
      labels:
        app: php-site
    spec:
      containers:
      - name: php7
        image: php_apache_site
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: task-pv-storage
          mountPath: /var/www/html
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim

